"""empty message

Revision ID: 5f8e6b5f5d17
Revises: cbf17d226f9e
Create Date: 2024-07-01 23:33:40.337703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8e6b5f5d17'
down_revision = 'cbf17d226f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito__planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito__vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorito_vehiculo')
    op.drop_table('favorito_planeta')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nombre')

    op.create_table('favorito_planeta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], name='favorito_planeta_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorito_planeta_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_planeta_pkey')
    )
    op.create_table('favorito_vehiculo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorito_vehiculo_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], name='favorito_vehiculo_vehiculo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_vehiculo_pkey')
    )
    op.drop_table('favorito__vehiculo')
    op.drop_table('favorito__planeta')
    # ### end Alembic commands ###
